const translations = {
  el: {
    "main-title": "Α.Μ.Κ.Ε. ΔΙΕΘΝΗΣ ΔΡΑΣΗ",
    "subtitle": "INTERACTION",
    "slogan": "Σύγχρονη Πολιτιστική Παρουσία με Παγκόσμια Προοπτική",
    "nav-home": "ΑΡΧΙΚΗ",
    "nav-about": "ΣΧΕΤΙΚΑ",
    "actions": "ΔΡΑΣΕΙΣ",
    "nav-culture": "Πολιτισμός",
    "nav-tourism": "Τουρισμός",
    "nav-environment": "Περιβάλλον",
    "nav-education": "Εκπαίδευση",
    "nav-technology": "Τεχνολογία",
    "participation": "ΣΥΜΜΕΤΟΧΗ",
    "nav-volunteer": "Γίνε Εθελοντής",
    "nav-member": "Γίνε Μέλος",
    "nav-sponsor": "Γίνε Χορηγός",
    "nav-contact": "ΕΠΙΚΟΙΝΩΝΙΑ",
    "about-title": "Σχετικά με εμάς",
    "about-text": "Η <strong>Α.Μ.Κ.Ε. ΔΙΕΘΝΗΣ ΔΡΑΣΗ - INTERACTION</strong> είναι μια Αστική Μη Κερδοσκοπική Εταιρεία που δραστηριοποιείται στον τομέα του πολιτισμού, της τέχνης και της δημιουργικότητας. Σκοπός μας είναι η ενίσχυση της προσφοράς της Ελλάδας και των σύγχρονων Ελλήνων καλλιτεχνών και δημιουργών στην παγκόσμια πολιτιστική αρένα μέσα από συνεργασίες, φεστιβάλ, εκπαιδευτικά προγράμματα και καλλιτεχνικές παραγωγές.",
    "typing-text": "Προβάλλουμε τον Ελληνικό Πολιτισμό Διεθνώς",
    "projects-title": "Δράσεις",
    "join-us-title": "Δήλωσε Συμμετοχή",
    "join-us-member": "Γίνε μέλος:",
    "join-us-member-description": "Η συμμετοχή σου ως μέλος της ομάδας μας δεν είναι απλώς μια εγγραφή — είναι μια πράξη δέσμευσης προς έναν καλύτερο κόσμο. Ως μέλος, έχεις τη δυνατότητα να συμμετέχεις ενεργά στις δράσεις μας και να γίνεις μέρος μιας κοινότητας με κοινές αξίες.",
    "join-us-volunteer": "Γίνε εθελοντής:",
    "join-us-volunteer-description": "Αν θέλεις να προσφέρεις χρόνο, δημιουργικότητα και ενέργεια, μπορείς να συμβάλεις στις δράσεις μας και να αποκτήσεις πολύτιμες εμπειρίες μέσα από την προσφορά.",
    "join-us-button": "Μάθε περισσότερα",
    "contact-title": "Επικοινωνήστε μαζί μας",
    "footer-text": "© Α.Μ.Κ.Ε. ΔΙΕΘΝΗΣ ΔΡΑΣΗ - INTERACTION | All rights reserved",
    "about-description": "Η <strong>Αστική Μη Κερδοσκοπική Εταιρία ΔΙΕΘΝΗΣ ΔΡΑΣΗ – INTERACTION</strong> ιδρύθηκε το 2024, έχοντας ως κεντρικό άξονα τη σύνδεση της Ελλάδας του σήμερα με τον υπόλοιπο κόσμο.",
    "main-goals-title": "Βασικοί σκοποί μας αποτελούν:",
    "goal-1": "Η ενίσχυση της προσφοράς της Ελλάδας και των σύγχρονων Ελλήνων καλλιτεχνών και δημιουργών στην παγκόσμια πολιτιστική αρένα",
    "goal-2": "Η σύνδεση του Απόδημου Ελληνισμού παγκοσμίως με την Ελλάδα του σήμερα",
    "goal-3": "Η προβολή του σύγχρονου ελληνικού πολιτισμού και η προώθηση της τέχνης, της λογοτεχνίας, της μουσικής και άλλων πτυχών του πολιτισμού",
    "goal-4": "Η ανάπτυξη πρωτοβουλιών για την προώθηση τουριστικών δραστηριοτήτων",
    "goal-5": "Η προστασία του περιβάλλοντος και η αναβάθμιση του τόπου και της ποιότητας ζωής των κατοίκων της Ελλάδας",
    "goal-6": "Η συμμετοχή σε πρωτοβουλίες για την προστασία του περιβάλλοντος και η ανάπτυξη της οικολογικής γνώσης και συνείδησης",
    "goal-7": "Η διαχείριση απορριμμάτων και ενέργειας",
    "goal-8": "Η προώθηση των επιστημών και της εκπαίδευσης μέσω συνεργασιών με ελληνικά και διεθνή πανεπιστήμια",
    "goal-9": "Η εφαρμογή τεχνητής νοημοσύνης σε διάφορους τομείς",
    "goal-10": "Η αξιοποίηση της τεχνονολογίας και της καινοτομίας",
    "collaboration-text": "Η ανάπτυξη της δράσης της <STRONG>Α.Μ.Κ.Ε. ΔΙΕΘΝΗΣ ΔΡΑΣΗ – INTERACTION </STRONG>πραγματοποιείται σε συνεργασία με χώρες από όλο τον κόσμο, όπου υπάρχει ανάγκη και προοπτική συνεργασίας.",
    "service-intro": "Για την εξυπηρέτηση και προώθηση των σκοπών της η Α.Μ.Κ.Ε. ΔΙΕΘΝΗΣ ΔΡΑΣΗ – INTERACTION:",
    "service-1": "Οργανώνει εκδηλώσεις",
    "service-2": "Συνεργάζεται με αντίστοιχες οργανώσεις και φορείς στην Ελλάδα και το εξωτερικό",
    "service-3": "Συμμετέχει σε δίκτυα πανελλήνιας, περιφερειακής και διεθνούς εμβέλειας",
    "service-4": "Διοργανώνει πολιτιστικές δράσεις, εκπαιδευτικά προγράμματα και σεμινάρια σε διάφορους τομείς",
    "service-5": "Φροντίζει για την εκπαίδευση των νέων σε θέματα περιβαλλοντικής συνείδησης",
    "service-6": "Διοργανώνει εκθέσεις, παραστάσεις, συναυλίες και προγράμματα που προάγουν τον πολιτισμό στο εξωτερικό",
    "service-7": "Προβάλλει τουριστικούς προορισμούς, οργανίζει ταξίδια και δράσεις που αναδεικνύουν την πολιτιστική κληρονομιά",
    "service-8": "Πραγματοποιεί ημερίδες με θέματα περιβαλλοντικά και επιστημονικά",
    "service-9": "Συνεργάζεται με εκπαιδευτικά ιδρύματα και πανεπιστήμια του εξωτερικού",
    "ticker-1": "Ενίσχυση και προβολή του σύγχρονου ελληνικού πολιτισμού Παγκοσμίως",
    "ticker-2": "Σύνδεση του τουρισμού με την προβολή του σύγχρονου πολιτισμού",
    "ticker-3": "Προβολή ενός σύγχρονου \"πολιτιστικού\" διάστασης της περιβαλλοντικής συνείδησης",
    "ticker-4": "Σύνδεση της εκπαίδευσης με την προβολή του σύγχρονου ελληνικού πνεύματος",
    "ticker-5": "Ένταξη της τεχνολογίας στην ευρύτερη έννοια του σύγχρονου πολιτισμού",
    "btn-culture": "Πολιτισμός",
    "btn-tourism": "Τουρισμός",
    "btn-environment": "Περιβάλλον",
    "btn-education": "Εκπαίδευση",
    "btn-technology": "Τεχνολογία",
    "square-1": "Συμμετοχές σε Projects",
    "square-2": "Διεθνείς Συνεργασίες",
    "square-3": "Εκδηλώσεις",
    "square-4": "Πολιτιστικά Προγράμματα",
    "partners-title": "Συνεργάτες - Υποστηρικτές",
    "culture-title": "Πολιτισμός",
    "culture-description": "Η Α.Μ.Κ.Ε. ΔΙΕΘΝΗΣ ΔΡΑΣΗ – INTERACTION ενισχύει και προβάλλει τον σύγχρονο ελληνικό πολιτισμό παγκοσμίως. Σκοπός μας είναι να στηρίξουμε τους Έλληνες δημιουργούς, να διαδώσουμε την ελληνική τέχνη, μουσική, λογοτεχνία και να δημιουργήσουμε γέφυρες πολιτισμού με άλλες χώρες.",
    "exhibition-title": "Διοργάνωση εκθέσεων, συναυλιών, παραστάσεων στην Ελλάδα και το εξωτερικό",
    "exhibition-description": "Η Α.Μ.Κ.Ε. ΔΙΕΘΝΗΣ ΔΡΑΣΗ - INTERACTION αναλαμβάνει τη διοργάνωση και προώθηση εκθέσεων εικαστικών τεχνών, συναυλιών μουσικής, θεατρικών παραστάσεων και άλλων πολιτιστικών εκδηλώσεων. Στοχεύουμε στην ανάδειξη του έργου Ελλήνων και διεθνών καλλιτεχνών σε καταξιωμένους χώρους εντός και εκτός Ελλάδας, προσφέροντας στο κοινό υψηλής ποιότητας πολιτιστικές εμπειρίες και ενισχύοντας την πολιτιστική παραγωγή.",
    "cultural-exchange-title": "Πολιτιστικές ανταλλαγές με διεθνείς καλλιτεχνικούς οργανισμούς",
    "cultural-exchange-description": "Θεωρούμε τις πολιτιστικές ανταλλαγές θεμελιώδεις για την αλληλοκατανόηση και την ανάπτυξη. Συνεργαζόμαστε ενεργά με διεθνείς καλλιτεχνικούς οργανισμούς, ιδρύματα και φορείς για την υλοποίηση κοινών προγραμμάτων, φιλοξενίες καλλιτεχνών και ανταλλαγή τεχνογνωσίας. Αυτές οι δράσεις ενισχύουν τους δεσμούς μεταξύ των πολιτισμών και δίνουν την ευκαιρία στους Έλληνες δημιουργούς να έρθουν σε επαφή με διαφορετικές καλλιτεχνικές προσεγγίσεις και κοινό.",
    "showcase-creators-title": "Προβολή Ελλήνων δημιουργών μέσω διεθνών συνεργασιών",
    "showcase-creators-description": "Είναι προτεραιότητα μας η συστηματική προβολή των Ελλήνων δημιουργών στο διεθνές καλλιτεχνικό στερέωμα. Μέσα από συμμετοχές σε διεθνή φεστιβάλ, εκθέσεις, συνέδρια και συνεργασίες με γκαλερί και πολιτιστικούς φορείς του εξωτερικού, επιδιώκουμε να αναδείξουμε το ταλέντο και την πρωτοτυπία της σύγχρονης ελληνικής δημιουργίας, διευρύνοντας το κοινό τους και ανοίγοντας νέους δρόμους στην καριέρα τους.",
    "global-networks-title": "Συμμετοχή σε παγκόσμια πολιτιστικά δίκτυα",
    "global-networks-description": "Η ενεργός συμμετοχή μας σε διεθνή πολιτιστικά δίκτυα και πλατφόρμες είναι ζωτικής σημασίας για την επίτευξη των στόχων μας. Μέσω αυτών των δικτύων, ανταλλάσσουμε ιδέες, συμμετέχουμε σε συζητήσεις για τις σύγχρονες τάσεις στον πολιτισμό, αναπτύσσουμε συνεργασίες και διασυνδεόμαστε με άλλους επαγγελματίες και οργανισμούς από όλο τον κόσμο. Αυτή η διασύνδεση ενισχύει την ορατότητα της ελληνικής πολιτιστικής σκηνής και συμβάλλει στην παγκόσμια πολιτιστική πολυμορφία.",
    "tourism-title": "Τουρισμός",
    "tourism-description": "Η Α.Μ.Κ.Ε. ΔΙΕΘΝΗΣ ΔΡΑΣΗ – INTERACTION αναπτύσσει πρωτοβουλίες για την προώθηση τουριστικών δραστηριοτήτων, αναδεικνύοντας την πλούσια πολιτιστική κληρονομιά και τους μοναδικούς προορισμούς της Ελλάδας σε παγκόσμιο επίπεδο. Στόχος μας είναι η βιώσιμη τουριστική ανάπτυξη και η προβολή της σύγχρονης ελληνικής ταυτότητας.",
    "tourism-destinations-title": "Προβολή Τουριστικών Προορισμών",
    "tourism-destinations-description": "Προβάλλουμε τουριστικούς προορισμούς στην Ελλάδα, αναδεικνύοντας την ιστορία, τον πολιτισμό, τη φυσική ομορφιά και τις σύγχρονες υποδομές τους. Μέσω της δημιουργίας και διάδοσης ποιοτικού υλικού, στοχεύουμε στην προσέλκυση επισκεπτών από όλο τον κόσμο.",
    "tourism-travel-title": "Οργάνωση Ταξιδιών και Δράσεων",
    "tourism-travel-description": "Οργανώνουμε ταξί",
    "environment-title": "Περιβάλλον",
    "environment-description": "Η Α.Μ.Κ.Ε. ΔΙΕΘΝΗΣ ΔΡΑΣΗ – INTERACTION δεσμεύεται στην προστασία του περιβάλλοντος και την προώθηση της βιώσιμης ανάπτυξης. Μέσω των δράσεών μας, επιδιώκουμε την αναβάθμιση του τόπου, τη βελτίωση της ποιότητας ζωής των κατοίκων και την ανάπτυξη της οικολογικής γνώσης και συνείδησης.",
    "environment-initiative-title": "Συμμετοχή σε Πρωτοβουλίες Προστασίας Περιβάλλοντος",
    "environment-initiative-description": "Συμμετέχουμε ενεργά σε πρωτοβουλίες που στοχεύουν στην προστασία του φυσικού περιβάλλοντος. Στηρίζουμε και υλοποιούμε δράσεις για τη διατήρηση της βιοποικιλότητας, την προστασία των οικοσυστημάτων και την αντιμετώπιση των περιβαλλοντικών προκλήσεων.",
    "environment-education-title": "Ανάπτυξη Οικολογικής Γνώσης και Συνείδησης",
    "environment-education-description": "Επενδύουμε στην εκπαίδευση και ευαισθητοποίηση του κοινού, ιδιαίτερα των νέων, σε θέματα περιβαλλοντικής προστασίας. Διοργανώνουμε εκπαιδευτικά προγράμματα, σεμινάρια και εκδηλώσεις που ενθαρρύνουν την κατανόηση των περιβαλλοντικών ζητημάτων και την υιοθέτηση υπεύθυνων συμπο",
    "environment-waste-energy-title": "Προώθηση Βέλτιστων Πρακτικών Διαχείρισης Απορριμμάτων και Ενέργειας",
    "environment-waste-energy-description": "Αναπτύσσουμε και προωθούμε πρωτοβουλίες για τη βελτίωση της διαχείρισης απορριμμάτων και την εξοικονόμηση ενέργειας. Ενημερώνουμε για σύγχρονες πρακτικές ανακύκλωσης, κομποστοποίησης και χρήσης ανανεώσιμων πηγών ενέργειας, συμβάλλοντας σε ένα πιο βιώσιμο μέλλον.",
    "environment-seminars-title": "Πραγματοποίηση Ημερίδων με Περιβαλλοντικά Θέματα",
    "environment-seminars-description": "Διοργανώνουμε ημερίδες και εκδηλώσεις που εστιάζουν σε επίκαιρα περιβαλλοντικά ζητήματα. Συγκεντρώνουμε ειδικούς, ακαδημαϊκούς και φορείς για την ανταλλαγή γνώσεων, την παρουσίαση ερευνών και τη συζήτηση λύσεων για την προστασία του περιβάλλοντος.",
    "education-title": "Εκπαίδευση",
    "education-description": "Η Α.Μ.Κ.Ε. ΔΙΕΘΝΗΣ ΔΡΑΣΗ – INTERACTION εστιάζει στην προώθηση της εκπαίδευσης σε διάφορους τομείς, ενισχύοντας τη γνώση, την ανάπτυξη δεξιοτήτων και τη διεθνή συνεργασία στον ακαδημαϊκό χώρο. Στόχος μας είναι η συμβολή στη διά βίου μάθηση και την επιστημονική κατάρτιση.",
    "education-collab-title": "Συνεργασίες με Εκπαιδευτικά Ιδρύματα και Πανεπιστήμια",
    "education-collab-description": "Αναπτύσσουμε στρατηγικές συνεργασίες με ελληνικά και διεθνή εκπαιδευτικά ιδρύματα και πανεπιστήμια. Μέσα από κοινά προγράμματα, ερευνητικές πρωτοβουλίες και ανταλλαγές, επιδιώκουμε την προαγωγή της ακαδημαϊκής αριστείας, τη γεφύρωση του χάσματος μεταξύ θεωρίας και πράξης και τη δημιουργία διεθνών ευκαιριών για φοιτητές και ακαδημαϊκούς.",
    "education-programs-title": "Διοργάνωση Εκπαιδευτικών Προγραμμάτων και Σεμινάριων",
    "education-programs-description": "Οργανώνουμε και υλοποιούμε εκπαιδευτικά προγράμματα και σεμινάρια σε ποικίλα θέματα, καλύπτοντας διαφορετικούς επιστημονικούς και κοινωνικούς τομείς. Αυτές οι δράσεις απευθύνονται σε ένα ευρύ κοινό, με στόχο την ανάπτυξη νέων δεξιοτήτων, την επικαιροποίηση γνώσεων και την ενίσχυση της προσωπικής και επαγγελματικής κατάρτισης.",
    "education-environment-title": "Εκπαίδευση Νέων σε Θέματα Περιβαλλοντικής Συνείδησης",
    "education-environment-description": "Θεωρούμε την περιβαλλοντική εκπαίδευση των νέων θεμελιώδη για ένα βιώσιμο μέλλον. Δημιουργούμε και υποστηρίζουμε προγράμματα που ευαισθητοποιούν και ενημερώνουν τους νέους για τα περιβαλλοντικά ζητήματα, ενθαρρύνοντας την ανάπτυξη οικολογικής συνείδησης και την υιοθέτηση υπεύθυνων συμπο",
    "education-conferences-title": "Πραγματοποίηση Ημερίδων και Εκδηλώσεων Επιστημονικού Ενδιαφέροντος",
    "education-conferences-description": "Διοργανώνουμε ημερίδες και εκδηλώσεις με επίκεντρο θέματα επιστημονικού ενδιαφέροντος, συμπεριλαμβανομένων των περιβαλλοντικών επιστημών. Αυτές οι συναντήσεις αποτελούν πλατφόρμα για την παρουσίαση έρευνας, την ανταλλαγή ιδεών και τη συζήτηση για τις τελευταίες εξελίξεις, προάγοντας τον επιστημονικό διάλογο και τη διάδοση της γνώσης.",
    "tech-title": "Τεχνολογία",
    "tech-description": "Η Α.Μ.Κ.Ε. ΔΙΕΘΝΗΣ ΔΡΑΣΗ – INTERACTION αγκαλιάζει την τεχνολογία και την καινοτομία ως κεντρικούς πυλώνες για την επίτευξη των στόχων της. Επιδιώκουμε την αξιοποίηση σύγχρονων ψηφιακών εργαλείων και την προώθηση πρωτοποριακών λύσεων σε όλους τους τομείς δράσης μας.",
    "tech-innovation-title": "Αξιοποίηση Τεχνολογίας και Προώθηση Καινοτομίας",
    "tech-innovation-description": "Στηρίζουμε ενεργά την ενσωμάτωση της τεχνολογίας και την καλλιέργεια της καινοτομίας σε όλους τους τομείς δράσης μας. Ενθαρρύνουμε την υιοθέτηση νέων ψηφιακών εργαλείων, πλατφορμών και μεθοδολογιών που βελτιώνουν τις διαδικασίες, προωθούν την έρευνα και συμβάλλουν στην ανάπτυξη πρωτοποριακών λύσεων για σύγχρονες προκλήσεις.",
    "tech-ai-title": "Εφαρμογή Τεχνητής Νοημοσύνης σε Διάφορους Τομείς",
    "tech-ai-description": "Διερευνούμε και προωθούμε την υπεύθυνη εφαρμογή της Τεχνητής Νοημοσύνης (ΑΙ) σε διάφορους τομείς δράσης μας, από την εκπαίδευση και τον πολιτισμό έως την προστασία του περιβάλλοντος. Αναδεικνύουμε τις δυνατότητες της ΑΙ για την ανάλυση δεδομένων, την αυτοματοποίηση διαδικασιών και την υποστήριξη πρωτοβουλιών, συμβάλλοντας στην αξιοποίηση των νέων τεχνολογιών προς όφελος της κοινωνίας.",
    "tech-edu-innovation-title": "Αξιοποίηση Τεχνολογίας και Προώθηση Καινοτομίας στην Εκπαίδευση",
    "tech-edu-innovation-description": "Στηρίζουμε ενεργά την ενσωμάτωση της τεχνολογίας και την καλλιέργεια της καινοτομίας στην εκπαίδευση και την επιστήμη. Ενθαρρύνουμε την υιοθέτηση ψηφιακών εργαλείων και μεθοδολογιών που βελτιώνουν τη μάθηση, προωθούν την έρευνα και συμβάλλουν στην ανάπτυξη πρωτοποριακών λύσεων.",
    "tech-ai-edu-title": "Εφαρμογή Τεχνητής Νοημοσύνης στην Εκπαίδευση και Έρευνα",
    "tech-ai-edu-description": "Διερευνούμε και προωθούμε την υπεύθυνη εφαρμογή της Τεχνητής Νοημοσύνης (ΑΙ) στον εκπαιδευτικό και επιστημονικό χώρο. Αναδεικνύουμε τις δυνατότητες της ΑΙ για εξατομίκευση μάθησης, ανάλυση δεδομένων, αυτοματοποίηση διαδικασιών και υποστήριξη της έρευνας.",
    "join-section-title": "Δήλωσε Συμμετοχή",
    "join-member-label": "Γίνε μέλος:",
    "join-member-text": "Η συμμετοχή σου ως μέλος της ομάδας μας δεν είναι απλώς μια εγγραφή — είναι μια πράξη δέσμευσης προς έναν καλύτερο κόσμο. Ως μέλος, έχεις τη δυνατότητα να συμμετέχεις ενεργά στις δράσεις μας και να γίνεις μέρος μιας κοινότητας με κοινές αξίες. Θα έχεις την ευκαιρία να συνεισφέρεις στο κοινωνικό σύνολο, να αποκτήσεις νέες γνώσεις και να δημιουργήσεις διαρκείς σχέσεις με άλλους ανθρώπους που μοιράζονται τις ίδιες φιλοσοφίες και στόχους.",
    "join-volunteer-label": "Γίνε εθελοντής:",
    "join-volunteer-text": "Αν θέλεις να προσφέρεις χρόνο, δημιουργικότητα και ενέργεια, μπορείς να συμβάλεις στις δράσεις μας και να αποκτήσεις πολύτιμες εμπειρίες μέσα από την προσφορά. Εθελοντισμός σημαίνει συμμετοχή σε δράσεις που βοηθούν στην προώθηση του πολιτισμού, της εκπαίδευσης και της κοινωνικής αλληλεγγύης, και σου δίνει τη δυνατότητα να συμβάλεις ενεργά σε έργα που κάνουν τη διαφορά στην κοινότητα.",
    "join-conclusion": "Με την ενεργή συμμετοχή σου, δεν προσφέρεις μόνο στους άλλους, αλλά αναπτύσσεσαι και εσύ προσωπικά. Γίνε κομμάτι μιας ομάδας που λειτουργεί με όραμα και σκοπό, για έναν καλύτερο κόσμο για όλους!",
    "btn-volunteer": "Γίνε Εθελοντής",
    "btn-member": "Γίνε Μέλος",
    "volunteer-title": "Η Αξία του Εθελοντισμού",
    "volunteer-text-1": "Ο εθελοντισμός είναι μια ανεκτίμητη πράξη προσφοράς προς την κοινωνία και τον κόσμο γύρω μας. Ο εθελοντής προσφέρει χρόνο, ενέργεια και ικανότητες για την υποστήριξη δράσεων που στοχεύουν σε ένα καλύτερο μέλλον για όλους μας. Εθελοντισμός δεν είναι μόνο η συμμετοχή σε δραστηριότητες, είναι η ευκαιρία να αλλάξουμε την κοινωνία και να προσφέρουμε σε άλλους χωρίς αντάλλαγμα. Η εμπειρία του εθελοντή είναι μια εμπειρία αναγνώρισης, εξέλιξης και συνεισφοράς.",
    "volunteer-text-2": "Όταν συμμετέχουμε ως εθελοντές, προσφέρουμε όχι μόνο βοήθεια, αλλά και την ευκαιρία για προσωπική ανάπτυξη. Ενισχύουμε την κοινότητα, διευρύνουμε τους ορίζοντές μας και μαθαίνουμε μέσα από τις εμπειρίες μας. Ο εθελοντισμός προσφέρει την ευκαιρία να συνεργαστούμε με άλλους ανθρώπους, να εμπλουτίσουμε τις γνώσεις μας και να γίνουμε μέρος μιας ομάδας που εργάζεται για έναν κοινό σκοπό.",
    "volunteer-text-3": "Αν θέλεις να βοηθήσεις, γεμάτος ενθουσιασμό και διάθεση, γίνε μέλος της ομάδας μας και εθελοντής στις δράσεις μας. Μάθε πώς μπορείς να προσφέρεις στον κόσμο γύρω σου και να εξελιχθείς με το έργο μας!",
    "volunteer-btn-form": "Συμπλήρωσε τη φόρμα συμμετοχής",
    "volunteer-btn-back": "Γύρισε πίσω",
    "modal-title": "Φόρμα Εγγραφής",
    "form-fullName": "Ονοματεπώνυμο",
    "form-email": "Email",
    "form-phone": "Τηλέφωνο",
    "form-city": "Τόπος Κατοικίας",
    "form-address": "Διεύθυνση",
    "form-message": "Γράψε το μήνυμά σου εδώ...",
    "form-submit": "Υποβολή",
    "member-title": "Γίνε Μέλος",
    "member-description": "Όταν γίνεσαι μέλος της κοινότητας μας, αποκτάς πρόσβαση σε δράσεις, εκδηλώσεις και ευκαιρίες για να αναπτύξεις τις ικανότητές σου και να συνεισφέρεις στην κοινωνία μας",
    "member-description1": "Ετήσια Συνδρομή Εγγραφής 100€ ",
    "member-benefits-title": "Πλεονεκτήματα του να Είσαι Μέλος",
    "benefit-1": "Πρόσβαση σε Αποκλειστικές Δράσεις και Εκδηλώσεις – Από εκπαιδευτικά σεμινάρια και πολιτιστικά φεστιβάλ έως διεθνή συνέδρια, η συμμετοχή σου συμβάλλει στην προσωπική σου εξέλιξη",
    "benefit-2": "Ειδικές Τιμές και Εκπτώσεις στα εισητήρια και πρόσβαση για όλες τις εκδηλώσεις και δρώμενα του Φεστιβάλ εντός και εκτός Ελλάδας",
    "benefit-3": "Ειδικές Τιμές στους προορισμούς του φεστιβάλ σε ξενοδοχεία, εστιατόρια, μετακίνηση",
    "benefit-4": "Δικτύωση με Κορυφαίους Επαγγελματίες και Δημιουργικούς Ανθρώπους – Δημιουργία ισχυρών συνεργασιών και ανταλλαγή ιδεών με άτομα που μοιράζονται τις ίδιες αξίες και στόχους",
    "benefit-5": "Πρόσβαση σε Μοναδικά Εκπαιδευτικά Προγράμματα – Εξειδικευμένα προγράμματα για την ανάπτυξη ηγετικών ικανοτήτων και την εκμάθηση νέων τεχνολογιών",
    "benefit-6": "Ευκαιρίες Εθελοντισμού και Κοινωνικής Προσφοράς – Συμμετοχή σε δράσεις που ενισχύουν την κοινωνική πρόοδο και αλληλεγγύη",
    "benefit-7": "Δημιουργία και Υποστήριξη Προσωπικών Έργων – Βοήθεια στην ανάπτυξη και χρηματοδότηση των δικών σου καινοτόμων έργων και πρωτοβουλιών",
    "benefit-8": "Αίσθηση Συνοχής και Ανήκειν – Γίνε μέρος μιας κοινότητας που στηρίζει την κοινωνική αλλαγή και τη συνεχιζόμενη εξέλιξη των μελών της",
    "btn-fill-form": "Συμπλήρωσε τη φόρμα συμμετοχής",
    "btn-go-back": "Γύρισε πίσω",
    "form-name": "Το όνομά σας",
    "contact-email": "Το email σας",
    "contact-message": "Μήνυμά σας",
    "contact-submit": "Αποστολή",
    "info-title": "Στοιχεία Επικοινωνίας",
    "info-address": "Διεύθυνση:<br> Λάμπρου Κατσώνη 51, Αθήνα, Τ.Κ. 11471",
    "info-phone": "Τηλέφωνο:<br> +30 211 2154573 ",
    "info-email": "Email:<br> amkeinteraction@gmail.com",
    "follow-title": "Ακολουθήστε μας",
    "social-facebook": "Facebook",
    "social-instagram": "Instagram",
    "social-google": "Google Business",
    "btn-sponsor": "Γίνε Χορηγός",
    "join-sponsor-label": "Γίνε Χορηγός:",
    "join-sponsor-text": "Η υποστήριξη σου ως χορηγός είναι ζωτικής σημασίας για την υλοποίηση των δράσεων μας. Η προσφορά σου, είτε οικονομική είτε σε είδος, μας επιτρέπει να μετατρέψουμε το όραμα μας σε πραγματικότητα και να φέρουμε εις πέρας projects με σημαντικό αντίκτυπο. Ως χορηγός, ενισχύεις το έργο μας και παράλληλα προβάλλεις την επιχείρησή σου, συνδέοντας την με αξίες όπως ο πολιτισμός, η κοινωνική προσφορά και η καινοτομία. Είναι μια ευκαιρία να δείξεις την εταιρική σου ευθύνη και να γίνεις συν-δημιουργός σε πρωτοβουλίες που εμπνέουν και αλλάζουν.",
    "join-us-sponsor-description": "Ως χορηγός, προβάλλετε την επιχείρησή σας συνδέοντάς την με τον πολιτισμό, την κοινωνική προσφορά και την καινοτομία. Δείξτε την εταιρική σας ευθύνη και γίνετε συν-δημιουργός αλλαγής.",
    "join-us-sponsor": "Γίνε χορηγός:",

    // Cookie Consent Translations (Ελληνικά)
    "cookie-message": "Αυτός ο ιστότοπος χρησιμοποιεί cookies για να διασφαλίσει ότι θα έχετε την καλύτερη εμπειρία στον ιστότοπό μας.",
    "cookie-accept": "Αποδοχή Cookies",
    "cookie-deny": "Απόρριψη",
    "cookie-learn-more": "Μάθετε περισσότερα",
    "cookie-privacy-policy-url": "el1.pdf",
    "accept-terms-text": "Διαβάστε και αποδεχτείτε τους <a href=\"el2.pdf\" target=\"_blank\">Όρους Χρήσης</a> και την <a href=\"el3.pdf\" target=\"_blank\">Πολιτική Απορρήτου</a>."

  },
  en: {
    "main-title": "A.M.K.E. DIETHNIS DRASI",
    "subtitle": "INTERACTION",
    "slogan": "Modern Cultural Presence with a Global Perspective",
    "nav-home": "HOME",
    "nav-about": "ABOUT",
    "actions": "PROJECTS",
    "nav-culture": "Culture",
    "nav-tourism": "Tourism",
    "nav-environment": "Environment",
    "nav-education": "Education",
    "nav-technology": "Technology",
    "participation": "PARTICIPATE",
    "nav-volunteer": "Become a Volunteer",
    "nav-member": "Become a Member",
    "nav-sponsor": "Become a Sponsor",
    "nav-contact": "CONTACT",
    "about-title": "About Us",
    "about-text": "<strong>A.M.K.E. DIETHNIS DRASI - INTERACTION</strong> is a Non-Profit Civil Company active in the fields of culture, art, and creativity. Our goal is to enhance Greece’s and modern Greek artists’ contribution to the global cultural scene through collaborations, festivals, educational programs, and artistic productions.",
    "typing-text": "We promote Greek Culture Internationally",
    "projects-title": "Projects",
    "join-us-title": "Join Us",
    "join-us-member": "Become a member:",
    "join-us-member-description": "Becoming a member of our team is not just a registration — it’s a commitment to a better world. As a member, you have the opportunity to actively participate in our actions and become part of a community with shared values",
    "join-us-volunteer": "Become a volunteer:",
    "join-us-volunteer-description": "If you want to offer time, creativity, and energy, you can contribute to our actions and gain valuable experience through giving",
    "join-us-button": "Learn more",
    "contact-title": "Contact Us",
    "footer-text": "© A.M.K.E. DIETHNIS DRASI - INTERACTION | All rights reserved",
    "about-description": "<strong>A.M.K.E. DIETHNIS DRASI – INTERACTION</strong> was founded in 2024, aiming to connect today’s Greece with the world.",
    "main-goals-title": "Our main goals include:",
    "goal-1": "Promoting the contribution of Greece and modern Greek artists and creators in the global cultural arena",
    "goal-2": "Connecting the Greek diaspora worldwide with today’s Greece",
    "goal-3": "Showcasing modern Greek culture and promoting art, literature, music, and other aspects of culture",
    "goal-4": "Developing initiatives for the promotion of tourism activities",
    "goal-5": "Protecting the environment and improving the living standards and quality of life in Greece",
    "goal-6": "Participating in initiatives for environmental protection and fostering ecological awareness",
    "goal-7": "Managing waste and energy",
    "goal-8": "Promoting science and education through partnerships with Greek and international universities",
    "goal-9": "Applying artificial intelligence across sectors",
    "goal-10": "Utilizing technology and innovation",
    "collaboration-text": "The activities of <STRONG>A.M.K.E. DIETHNIS DRASI – INTERACTION</STRONG> are carried out in collaboration with countries around the world where there is need and potential for cooperation.",
    "service-intro": "To serve and promote its objectives, A.M.K.E. DIETHNIS DRASI – INTERACTION:",
    "service-1": "Organizes events",
    "service-2": "Collaborates with similar organizations and agencies in Greece and abroad",
    "service-3": "Participates in national, regional, and international networks",
    "service-4": "Organizes cultural activities, educational programs, and seminars in various fields",
    "service-5": "Ensures youth education on environmental awareness",
    "service-6": "Hosts exhibitions, performances, concerts, and programs that promote culture abroad",
    "service-7": "Showcases tourist destinations, organizes trips and activities that highlight cultural heritage",
    "service-8": "Conducts conferences on environmental and scientific topics",
    "service-9": "Partners with educational institutions and universities abroad",
    "ticker-1": "Promoting modern Greek culture worldwide",
    "ticker-2": "Linking tourism with showcasing modern culture",
    "ticker-3": "Presenting a modern cultural dimension of environmental awareness",
    "ticker-4": "Connecting education with showcasing the modern Greek spirit",
    "ticker-5": "Integrating technology into the broader concept of modern culture",
    "btn-culture": "Culture",
    "btn-tourism": "Tourism",
    "btn-environment": "Environment",
    "btn-education": "Education",
    "btn-technology": "Technology",
    "square-1": "Project Participation",
    "square-2": "International Collaborations",
    "square-3": "Events",
    "square-4": "Cultural Programs",
    "partners-title": "Partners & Supporters",
    "culture-title": "Culture",
    "culture-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION promotes and showcases modern Greek culture worldwide. Our goal is to support Greek creators, spread Greek art, music, literature, and build cultural bridges with other countries.",
    "exhibition-title": "Organizing Exhibitions, Concerts, Performances in Greece and Abroad",
    "exhibition-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION takes on the organization and promotion of visual arts exhibitions, music concerts, theater performances, and other cultural events. We aim to showcase the works of Greek and international artists in renowned venues both in Greece and abroad, offering the public high-quality cultural experiences and strengthening cultural production.",
    "cultural-exchange-title": "Cultural Exchanges with International Artistic Organizations",
    "cultural-exchange-description": "We consider cultural exchanges essential for mutual understanding and development. We actively collaborate with international artistic organizations, institutions, and bodies to implement joint programs, host artists, and exchange know-how. These actions strengthen ties between cultures and give Greek creators the opportunity to engage with different artistic approaches and audiences.",
    "showcase-creators-title": "Showcasing Greek Creators Through International Collaborations",
    "showcase-creators-description": "Our priority is the systematic showcasing of Greek creators in the international art scene. Through participation in international festivals, exhibitions, conferences, and collaborations with galleries and cultural organizations abroad, we aim to highlight the talent and originality of contemporary Greek creation, expanding their audience and opening new paths in their careers.",
    "global-networks-title": "Participation in Global Cultural Networks",
    "global-networks-description": "Our active participation in international cultural networks and platforms is vital to achieving our goals. Through these networks, we exchange ideas, engage in discussions on contemporary trends in culture, develop collaborations, and connect with other professionals and organizations worldwide. This connectivity enhances the visibility of Greek cultural scenes and contributes to global cultural diversity.",
    "tourism-title": "Tourism",
    "tourism-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION develops initiatives to promote tourism activities, showcasing Greece’s rich cultural heritage and unique destinations globally. Our goal is sustainable tourism development and the promotion of modern Greek identity.",
    "tourism-destinations-title": "Showcasing Tourist Destinations",
    "tourism-destinations-description": "We showcase tourist destinations in Greece, highlighting their history, culture, natural beauty, and modern infrastructure. Through the creation and dissemination of high-quality material, we aim to attract visitors from around the world.",
    "tourism-travel-title": "Organizing Trips and Activities",
    "tourism-travel-description": "We organize trips and activities that highlight cultural heritage and local peculiarities. We design experiences that combine education, entertainment, and immersion in authentic Greek life, offering unique moments for visitors.",
    "environment-title": "Environment",
    "environment-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION is committed to environmental protection and promoting sustainable development. Through our actions, we aim to upgrade the area, improve the quality of life for residents, and develop ecological knowledge and awareness.",
    "environment-initiative-title": "Participation in Environmental Protection Initiatives",
    "environment-initiative-description": "We actively participate in initiatives that aim at protecting the natural environment. We support and implement actions to preserve biodiversity, protect ecosystems, and address environmental challenges.",
    "environment-education-title": "Development of Ecological Knowledge and Awareness",
    "environment-education-description": "We invest in educating and raising public awareness, especially among youth, on environmental protection issues. We organize educational programs, seminars, and events that encourage understanding of environmental issues and the adoption of responsible behaviors.",
    "environment-waste-energy-title": "Promotion of Best Practices in Waste and Energy Management",
    "environment-waste-energy-description": "We develop and promote initiatives to improve waste management and energy conservation. We inform about modern recycling, composting practices, and the use of renewable energy sources, contributing to a more sustainable future.",
    "environment-seminars-title": "Organizing Environmental Themed Seminars",
    "environment-seminars-description": "We organize seminars and events focusing on current environmental issues. We bring together experts, academics, and organizations to exchange knowledge, present research, and discuss solutions for environmental protection.",
    "education-title": "Education",
    "education-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION focuses on promoting education across various fields, enhancing knowledge, skill development, and international collaboration in academia. Our goal is to contribute to lifelong learning and scientific training.",
    "education-collab-title": "Partnerships with Educational Institutions and Universities",
    "education-collab-description": "We develop strategic partnerships with Greek and international educational institutions and universities. Through joint programs, research initiatives, and exchanges, we aim to promote academic excellence, bridge the gap between theory and practice, and create international opportunities for students and academics.",
    "education-programs-title": "Organizing Educational Programs and Seminars",
    "education-programs-description": "We organize and implement educational programs and seminars on various topics, covering diverse scientific and social fields. These activities target a wide audience, aiming to develop new skills, update knowledge, and enhance personal and professional training.",
    "education-environment-title": "Educating Youth on Environmental Awareness",
    "education-environment-description": "We consider environmental education for youth fundamental for a sustainable future. We create and support programs that raise awareness and inform young people about environmental issues, encouraging the development of ecological consciousness and the adoption of responsible practices for environmental protection.",
    "education-conferences-title": "Organizing Scientific Conferences and Events",
    "education-conferences-description": "We organize conferences and events focusing on scientific topics, including environmental sciences. These gatherings serve as a platform for presenting research, exchanging ideas, and discussing the latest developments, promoting scientific dialogue and knowledge dissemination.",
    "tech-title": "Technology",
    "tech-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION embraces technology and innovation as central pillars for achieving its goals. We seek to leverage modern digital tools and promote groundbreaking solutions in all our areas of activity.",
    "tech-innovation-title": "Leveraging Technology and Promoting Innovation",
    "tech-innovation-description": "We actively support the integration of technology and the cultivation of innovation across all our fields of action. We encourage the adoption of new digital tools, platforms, and methodologies that improve processes, advance research, and contribute to the development of pioneering solutions for contemporary challenges.",
    "tech-ai-title": "Applying Artificial Intelligence across various sectors",
    "tech-ai-description": "We explore and promote the responsible application of Artificial Intelligence (AI) across various sectors of our activities, from education and culture to environmental protection. We highlight AI's potential for data analysis, process automation, and initiative support, contributing to the utilization of new technologies for the benefit of society.",
    "tech-edu-innovation-title": "Leveraging Technology and Promoting Innovation in Education",
    "tech-edu-innovation-description": "We actively support the integration of technology and the cultivation of innovation in education and science. We encourage the adoption of digital tools and methodologies that improve learning, promote research and contribute to the development of pioneering solutions.",
    "tech-ai-edu-title": "Applying Artificial Intelligence in Education and Research",
    "tech-ai-edu-description": "We explore and promote the responsible application of Artificial Intelligence (AI) in the educational and scientific fields. We highlight AI's potential for personalized learning, data analysis, process automation, and research support.",
    "join-section-title": "Δήλωσε Συμμετοχή",
    "join-member-label": "Γίνε μέλος:",
    "join-member-text": "Η συμμετοχή σου ως μέλος της ομάδας μας δεν είναι απλώς μια εγγραφή — είναι μια πράξη δέσμευσης προς έναν καλύτερο κόσμο. Ως μέλος, έχεις τη δυνατότητα να συμμετέχεις ενεργά στις δράσεις μας και να γίνεις μέρος μιας κοινότητας με κοινές αξίες. Θα έχεις την ευκαιρία να συνεισφέρεις στο κοινωνικό σύνολο, να αποκτήσεις νέες γνώσεις και να δημιουργήσεις διαρκείς σχέσεις με άλλους ανθρώπους που μοιράζονται τις ίδιες φιλοσοφίες και στόχους.",
    "join-volunteer-label": "Γίνε εθελοντής:",
    "join-volunteer-text": "Αν θέλεις να προσφέρεις χρόνο, δημιουργικότητα και ενέργεια, μπορείς να συμβάλεις στις δράσεις μας και να αποκτήσεις πολύτιμες εμπειρίες μέσα από την προσφορά. Εθελοντισμός σημαίνει συμμετοχή σε δράσεις που βοηθούν στην προώθηση του πολιτισμού, της εκπαίδευσης και της κοινωνικής αλληλεγγύης, και σου δίνει τη δυνατότητα να συμβάλεις ενεργά σε έργα που κάνουν τη διαφορά στην κοινότητα.",
    "join-conclusion": "Με την ενεργή συμμετοχή σου, δεν προσφέρεις μόνο στους άλλους, αλλά αναπτύσσεσαι και εσύ προσωπικά. Γίνε κομμάτι μιας ομάδας που λειτουργεί με όραμα και σκοπό, για έναν καλύτερο κόσμο για όλους!",
    "btn-volunteer": "Γίνε Εθελοντής",
    "btn-member": "Γίνε Μέλος",
    "volunteer-title": "Η Αξία του Εθελοντισμού",
    "volunteer-text-1": "Ο εθελοντισμός είναι μια ανεκτίμητη πράξη προσφοράς προς την κοινωνία και τον κόσμο γύρω μας. Ο εθελοντής προσφέρει χρόνο, ενέργεια και ικανότητες για την υποστήριξη δράσεων που στοχεύουν σε ένα καλύτερο μέλλον για όλους μας. Εθελοντισμός δεν είναι μόνο η συμμετοχή σε δραστηριότητες, είναι η ευκαιρία να αλλάξουμε την κοινωνία και να προσφέρουμε σε άλλους χωρίς αντάλλαγμα. Η εμπειρία του εθελοντή είναι μια εμπειρία αναγνώρισης, εξέλιξης και συνεισφοράς.",
    "volunteer-text-2": "Όταν συμμετέχουμε ως εθελοντές, προσφέρουμε όχι μόνο βοήθεια, αλλά και την ευκαιρία για προσωπική ανάπτυξη. Ενισχύουμε την κοινότητα, διευρύνουμε τους ορίζοντές μας και μαθαίνουμε μέσα από τις εμπειρίες μας. Ο εθελοντισμός προσφέρει την ευκαιρία να συνεργαστούμε με άλλους ανθρώπους, να εμπλουτίσουμε τις γνώσεις μας και να γίνουμε μέρος μιας ομάδας που εργάζεται για έναν κοινό σκοπό.",
    "volunteer-text-3": "Αν θέλεις να βοηθήσεις, γεμάτος ενθουσιασμό και διάθεση, γίνε μέλος της ομάδας μας και εθελοντής στις δράσεις μας. Μάθε πώς μπορείς να προσφέρεις στον κόσμο γύρω σου και να εξελιχθείς με το έργο μας!",
    "volunteer-btn-form": "Συμπλήρωσε τη φόρμα συμμετοχής",
    "volunteer-btn-back": "Γύρισε πίσω",
    "modal-title": "Φόρμα Εγγραφής",
    "form-fullName": "Ονοματεπώνυμο",
    "form-email": "Email",
    "form-phone": "Τηλέφωνο",
    "form-city": "Τόπος Κατοικίας",
    "form-address": "Διεύθυνση",
    "form-message": "Γράψε το μήνυμά σου εδώ...",
    "form-submit": "Υποβολή",
    "member-title": "Γίνε Μέλος",
    "member-description": "Όταν γίνεσαι μέλος της κοινότητας μας, αποκτάς πρόσβαση σε δράσεις, εκδηλώσεις και ευκαιρίες για να αναπτύξεις τις ικανότητές σου και να συνεισφέρεις στην κοινωνία μας",
    "member-description1": "Ετήσια Συνδρομή Εγγραφής 100€ ",
    "member-benefits-title": "Πλεονεκτήματα του να Είσαι Μέλος",
    "benefit-1": "Πρόσβαση σε Αποκλειστικές Δράσεις και Εκδηλώσεις – Από εκπαιδευτικά σεμινάρια και πολιτιστικά φεστιβάλ έως διεθνή συνέδρια, η συμμετοχή σου συμβάλλει στην προσωπική σου εξέλιξη",
    "benefit-2": "Ειδικές Τιμές και Εκπτώσεις στα εισητήρια και πρόσβαση για όλες τις εκδηλώσεις και δρώμενα του Φεστιβάλ εντός και εκτός Ελλάδας",
    "benefit-3": "Ειδικές Τιμές στους προορισμούς του φεστιβάλ σε ξενοδοχεία, εστιατόρια, μετακίνηση",
    "benefit-4": "Δικτύωση με Κορυφαίους Επαγγελματίες και Δημιουργικούς Ανθρώπους – Δημιουργία ισχυρών συνεργασιών και ανταλλαγή ιδεών με άτομα που μοιράζονται τις ίδιες αξίες και στόχους",
    "benefit-5": "Πρόσβαση σε Μοναδικά Εκπαιδευτικά Προγράμματα – Εξειδικευμένα προγράμματα για την ανάπτυξη ηγετικών ικανοτήτων και την εκμάθηση νέων τεχνολογιών",
    "benefit-6": "Ευκαιρίες Εθελοντισμού και Κοινωνικής Προσφοράς – Συμμετοχή σε δράσεις που ενισχύουν την κοινωνική πρόοδο και αλληλεγγύη",
    "benefit-7": "Δημιουργία και Υποστήριξη Προσωπικών Έργων – Βοήθεια στην ανάπτυξη και χρηματοδότηση των δικών σου καινοτόμων έργων και πρωτοβουλιών",
    "benefit-8": "Αίσθηση Συνοχής και Ανήκειν – Γίνε μέρος μιας κοινότητας που στηρίζει την κοινωνική αλλαγή και τη συνεχιζόμενη εξέλιξη των μελών της",
    "btn-fill-form": "Συμπλήρωσε τη φόρμα συμμετοχής",
    "btn-go-back": "Γύρισε πίσω",
    "form-name": "Το όνομά σας",
    "contact-email": "Το email σας",
    "contact-message": "Μήνυμά σας",
    "contact-submit": "Αποστολή",
    "info-title": "Στοιχεία Επικοινωνίας",
    "info-address": "Διεύθυνση:<br> Λάμπρου Κατσώνη 51, Αθήνα, Τ.Κ. 11471",
    "info-phone": "Τηλέφωνο:<br> +30 211 2154573 ",
    "info-email": "Email:<br> amkeinteraction@mail.com",
    "follow-title": "Ακολουθήστε μας",
    "social-facebook": "Facebook",
    "social-instagram": "Instagram",
    "social-google": "Google Business",
    "btn-sponsor": "Γίνε Χορηγός",
    "join-sponsor-label": "Γίνε Χορηγός:",
    "join-sponsor-text": "Η υποστήριξη σου ως χορηγός είναι ζωτικής σημασίας για την υλοποίηση των δράσεων μας. Η προσφορά σου, είτε οικονομική είτε σε είδος, μας επιτρέπει να μετατρέψουμε το όραμα μας σε πραγματικότητα και να φέρουμε εις πέρας projects με σημαντικό αντίκτυπο. Ως χορηγός, ενισχύεις το έργο μας και παράλληλα προβάλλεις την επιχείρησή σου, συνδέοντας την με αξίες όπως ο πολιτισμός, η κοινωνική προσφορά και η καινοτομία. Είναι μια ευκαιρία να δείξεις την εταιρική σου ευθύνη και να γίνεις συν-δημιουργός σε πρωτοβουλίες που εμπνέουν και αλλάζουν.",
    "join-us-sponsor-description": "Ως χορηγός, προβάλλετε την επιχείρησή σας συνδέοντάς την με τον πολιτισμό, την κοινωνική προσφορά και την καινοτομία. Δείξτε την εταιρική σας ευθύνη και γίνετε συν-δημιουργός αλλαγής.",
    "join-us-sponsor": "Γίνε χορηγός:",

    // Cookie Consent Translations (Ελληνικά)
    "cookie-message": "Αυτός ο ιστότοπος χρησιμοποιεί cookies για να διασφαλίσει ότι θα έχετε την καλύτερη εμπειρία στον ιστότοπό μας.",
    "cookie-accept": "Αποδοχή Cookies",
    "cookie-deny": "Απόρριψη",
    "cookie-learn-more": "Μάθετε περισσότερα",
    "cookie-privacy-policy-url": "el1.pdf"
  },
  en: {
    "main-title": "A.M.K.E. DIETHNIS DRASI",
    "subtitle": "INTERACTION",
    "slogan": "Modern Cultural Presence with a Global Perspective",
    "nav-home": "HOME",
    "nav-about": "ABOUT",
    "actions": "PROJECTS",
    "nav-culture": "Culture",
    "nav-tourism": "Tourism",
    "nav-environment": "Environment",
    "nav-education": "Education",
    "nav-technology": "Technology",
    "participation": "PARTICIPATE",
    "nav-volunteer": "Become a Volunteer",
    "nav-member": "Become a Member",
    "nav-sponsor": "Become a Sponsor",
    "nav-contact": "CONTACT",
    "about-title": "About Us",
    "about-text": "<strong>A.M.K.E. DIETHNIS DRASI - INTERACTION</strong> is a Non-Profit Civil Company active in the fields of culture, art, and creativity. Our goal is to enhance Greece’s and modern Greek artists’ contribution to the global cultural scene through collaborations, festivals, educational programs, and artistic productions.",
    "typing-text": "We promote Greek Culture Internationally",
    "projects-title": "Projects",
    "join-us-title": "Join Us",
    "join-us-member": "Become a member:",
    "join-us-member-description": "Becoming a member of our team is not just a registration — it’s a commitment to a better world. As a member, you have the opportunity to actively participate in our actions and become part of a community with shared values",
    "join-us-volunteer": "Become a volunteer:",
    "join-us-volunteer-description": "If you want to offer time, creativity, and energy, you can contribute to our actions and gain valuable experience through giving",
    "join-us-button": "Learn more",
    "contact-title": "Contact Us",
    "footer-text": "© A.M.K.E. DIETHNIS DRASI - INTERACTION | All rights reserved",
    "about-description": "<strong>A.M.K.E. DIETHNIS DRASI – INTERACTION</strong> was founded in 2024, aiming to connect today’s Greece with the world.",
    "main-goals-title": "Our main goals include:",
    "goal-1": "Promoting the contribution of Greece and modern Greek artists and creators in the global cultural arena",
    "goal-2": "Connecting the Greek diaspora worldwide with today’s Greece",
    "goal-3": "Showcasing modern Greek culture and promoting art, literature, music, and other aspects of culture",
    "goal-4": "Developing initiatives for the promotion of tourism activities",
    "goal-5": "Protecting the environment and improving the living standards and quality of life in Greece",
    "goal-6": "Participating in initiatives for environmental protection and fostering ecological awareness",
    "goal-7": "Managing waste and energy",
    "goal-8": "Promoting science and education through partnerships with Greek and international universities",
    "goal-9": "Applying artificial intelligence across sectors",
    "goal-10": "Utilizing technology and innovation",
    "collaboration-text": "The activities of <STRONG>A.M.K.E. DIETHNIS DRASI – INTERACTION</STRONG> are carried out in collaboration with countries around the world where there is need and potential for cooperation.",
    "service-intro": "To serve and promote its objectives, A.M.K.E. DIETHNIS DRASI – INTERACTION:",
    "service-1": "Organizes events",
    "service-2": "Collaborates with similar organizations and agencies in Greece and abroad",
    "service-3": "Participates in national, regional, and international networks",
    "service-4": "Organizes cultural activities, educational programs, and seminars in various fields",
    "service-5": "Ensures youth education on environmental awareness",
    "service-6": "Hosts exhibitions, performances, concerts, and programs that promote culture abroad",
    "service-7": "Showcases tourist destinations, organizes trips and activities that highlight cultural heritage",
    "service-8": "Conducts conferences on environmental and scientific topics",
    "service-9": "Partners with educational institutions and universities abroad",
    "ticker-1": "Promoting modern Greek culture worldwide",
    "ticker-2": "Linking tourism with showcasing modern culture",
    "ticker-3": "Presenting a modern cultural dimension of environmental awareness",
    "ticker-4": "Connecting education with showcasing the modern Greek spirit",
    "ticker-5": "Integrating technology into the broader concept of modern culture",
    "btn-culture": "Culture",
    "btn-tourism": "Tourism",
    "btn-environment": "Environment",
    "btn-education": "Education",
    "btn-technology": "Technology",
    "square-1": "Project Participation",
    "square-2": "International Collaborations",
    "square-3": "Events",
    "square-4": "Cultural Programs",
    "partners-title": "Partners & Supporters",
    "culture-title": "Culture",
    "culture-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION promotes and showcases modern Greek culture worldwide. Our goal is to support Greek creators, spread Greek art, music, literature, and build cultural bridges with other countries.",
    "exhibition-title": "Organizing Exhibitions, Concerts, Performances in Greece and Abroad",
    "exhibition-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION takes on the organization and promotion of visual arts exhibitions, music concerts, theater performances, and other cultural events. We aim to showcase the works of Greek and international artists in renowned venues both in Greece and abroad, offering the public high-quality cultural experiences and strengthening cultural production.",
    "cultural-exchange-title": "Cultural Exchanges with International Artistic Organizations",
    "cultural-exchange-description": "We consider cultural exchanges essential for mutual understanding and development. We actively collaborate with international artistic organizations, institutions, and bodies to implement joint programs, host artists, and exchange know-how. These actions strengthen ties between cultures and give Greek creators the opportunity to engage with different artistic approaches and audiences.",
    "showcase-creators-title": "Showcasing Greek Creators Through International Collaborations",
    "showcase-creators-description": "Our priority is the systematic showcasing of Greek creators in the international art scene. Through participation in international festivals, exhibitions, conferences, and collaborations with galleries and cultural organizations abroad, we aim to highlight the talent and originality of contemporary Greek creation, expanding their audience and opening new paths in their careers.",
    "global-networks-title": "Participation in Global Cultural Networks",
    "global-networks-description": "Our active participation in international cultural networks and platforms is vital to achieving our goals. Through these networks, we exchange ideas, engage in discussions on contemporary trends in culture, develop collaborations, and connect with other professionals and organizations worldwide. This connectivity enhances the visibility of Greek cultural scenes and contributes to global cultural diversity.",
    "tourism-title": "Tourism",
    "tourism-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION develops initiatives to promote tourism activities, showcasing Greece’s rich cultural heritage and unique destinations globally. Our goal is sustainable tourism development and the promotion of modern Greek identity.",
    "tourism-destinations-title": "Showcasing Tourist Destinations",
    "tourism-destinations-description": "We showcase tourist destinations in Greece, highlighting their history, culture, natural beauty, and modern infrastructure. Through the creation and dissemination of high-quality material, we aim to attract visitors from around the world.",
    "tourism-travel-title": "Organizing Trips and Activities",
    "tourism-travel-description": "We organize trips and activities that highlight cultural heritage and local peculiarities. We design experiences that combine education, entertainment, and immersion in authentic Greek life, offering unique moments for visitors.",
    "environment-title": "Environment",
    "environment-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION is committed to environmental protection and promoting sustainable development. Through our actions, we aim to upgrade the area, improve the quality of life for residents, and develop ecological knowledge and awareness.",
    "environment-initiative-title": "Participation in Environmental Protection Initiatives",
    "environment-initiative-description": "We actively participate in initiatives that aim at protecting the natural environment. We support and implement actions to preserve biodiversity, protect ecosystems and address environmental challenges.",
    "environment-education-title": "Development of Ecological Knowledge and Awareness",
    "environment-education-description": "We invest in educating and raising public awareness, especially among youth, on environmental protection issues. We organize educational programs, seminars, and events that encourage understanding of environmental issues and the adoption of responsible behaviors.",
    "environment-waste-energy-title": "Promotion of Best Practices in Waste and Energy Management",
    "environment-waste-energy-description": "We develop and promote initiatives to improve waste management and energy conservation. We inform about modern recycling, composting practices, and the use of renewable energy sources, contributing to a more sustainable future.",
    "environment-seminars-title": "Organizing Environmental Themed Seminars",
    "environment-seminars-description": "We organize seminars and events focusing on current environmental issues. We bring together experts, academics, and organizations to exchange knowledge, present research, and discuss solutions for environmental protection.",
    "education-title": "Education",
    "education-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION focuses on promoting education across various fields, enhancing knowledge, skill development, and international collaboration in academia. Our goal is to contribute to lifelong learning and scientific training.",
    "education-collab-title": "Partnerships with Educational Institutions and Universities",
    "education-collab-description": "We develop strategic partnerships with Greek and international educational institutions and universities. Through joint programs, research initiatives, and exchanges, we aim to promote academic excellence, bridge the gap between theory and practice, and create international opportunities for students and academics.",
    "education-programs-title": "Organizing Educational Programs and Seminars",
    "education-programs-description": "We organize and implement educational programs and seminars on various topics, covering diverse scientific and social fields. These activities target a wide audience, aiming to develop new skills, update knowledge, and enhance personal and professional training.",
    "education-environment-title": "Educating Youth on Environmental Awareness",
    "education-environment-description": "We consider environmental education for youth fundamental for a sustainable future. We create and support programs that raise awareness and inform young people about environmental issues, encouraging the development of ecological consciousness and the adoption of responsible practices for environmental protection.",
    "education-conferences-title": "Organizing Scientific Conferences and Events",
    "education-conferences-description": "We organize conferences and events focusing on scientific topics, including environmental sciences. These gatherings serve as a platform for presenting research, exchanging ideas, and discussing the latest developments, promoting scientific dialogue and knowledge dissemination.",
    "tech-title": "Technology",
    "tech-description": "A.M.K.E. DIETHNIS DRASI - INTERACTION embraces technology and innovation as central pillars for achieving its goals. We seek to leverage modern digital tools and promote groundbreaking solutions in all our areas of activity.",
    "tech-innovation-title": "Leveraging Technology and Promoting Innovation",
    "tech-innovation-description": "We actively support the integration of technology and the cultivation of innovation across all our fields of action. We encourage the adoption of new digital tools, platforms, and methodologies that improve processes, advance research, and contribute to the development of pioneering solutions for contemporary challenges.",
    "tech-ai-title": "Applying Artificial Intelligence across various sectors",
    "tech-ai-description": "We explore and promote the responsible application of Artificial Intelligence (AI) across various sectors of our activities, from education and culture to environmental protection. We highlight AI's potential for data analysis, process automation, and initiative support, contributing to the utilization of new technologies for the benefit of society.",
    "tech-edu-innovation-title": "Leveraging Technology and Promoting Innovation in Education",
    "tech-edu-innovation-description": "We actively support the integration of technology and the cultivation of innovation in education and science. We encourage the adoption of digital tools and methodologies that improve learning, promote research and contribute to the development of pioneering solutions.",
    "tech-ai-edu-title": "Applying Artificial Intelligence in Education and Research",
    "tech-ai-edu-description": "We explore and promote the responsible application of Artificial Intelligence (AI) in the educational and scientific fields. We highlight AI's potential for personalized learning, data analysis, process automation, and research support.",
    "join-section-title": "Join Us",
    "join-member-label": "Become a member:",
    "join-member-text": "Becoming a member of our team is not just a registration — it’s a commitment to a better world. As a member, you have the opportunity to actively participate in our actions and become part of a community with shared values. You will have the opportunity to contribute to society, gain new knowledge, and build lasting relationships with other people who share the same philosophies and goals.",
    "join-volunteer-label": "Become a volunteer:",
    "join-volunteer-text": "If you want to offer time, creativity, and energy, you can contribute to our actions and gain valuable experience through giving. Volunteering means participating in actions that help promote culture, education, and social solidarity, and it gives you the opportunity to actively contribute to projects that make a difference in the community.",
    "join-conclusion": "Through your active participation, you not only offer to others but also grow personally. Become part of a team that operates with vision and purpose, for a better world for all!",
    "btn-volunteer": "Become a Volunteer",
    "btn-member": "Become a Member",
    "volunteer-title": "The Value of Volunteering",
    "volunteer-text-1": "Volunteering is an invaluable act of giving back to society and the world around us. A volunteer offers time, energy, and skills to support actions aimed at a better future for all of us. Volunteering is not just participating in activities; it is an opportunity to change society and offer to others without reward. The volunteer's experience is an experience of recognition, growth, and contribution.",
    "volunteer-text-2": "When we volunteer, we offer not only help but also an opportunity for personal growth. We strengthen the community, broaden our horizons, and learn through our experiences. Volunteering offers the opportunity to collaborate with other people, enrich our knowledge, and become part of a team working for a common purpose.",
    "volunteer-text-3": "If you want to help, full of enthusiasm and willingness, become a member of our team and a volunteer in our actions. Learn how you can give back to the world around you and grow with our work!",
    "volunteer-btn-form": "Fill out the participation form",
    "volunteer-btn-back": "Go back",
    "modal-title": "Registration Form",
    "form-fullName": "Full Name",
    "form-email": "Email",
    "form-phone": "Phone",
    "form-city": "City",
    "form-address": "Address",
    "form-message": "Write your message here...",
    "form-submit": "Submit",
    "member-title": "Become a Member",
    "member-description": "When you become a member of our community, you gain access to activities, events, and opportunities to develop your skills and contribute to our society",
    "member-description1": "Annual Membership Fee 100€",
    "member-benefits-title": "Benefits of Being a Member",
    "benefit-1": "Access to Exclusive Activities and Events – From educational seminars and cultural festivals to international conferences, your participation contributes to your personal development",
    "benefit-2": "Special Prices and Discounts on tickets and access for all events and happenings of the Festival in Greece and abroad",
    "benefit-3": "Special Prices at festival destinations for hotels, restaurants, transportation",
    "benefit-4": "Networking with Leading Professionals and Creative People – Building strong collaborations and exchanging ideas with individuals who share the same values and goals",
    "benefit-5": "Access to Unique Educational Programs – Specialized programs for developing leadership skills and learning new technologies",
    "benefit-6": "Volunteering and Social Contribution Opportunities – Participation in actions that enhance social progress and solidarity",
    "benefit-7": "Creation and Support of Personal Projects – Assistance in developing and funding your own innovative projects and initiatives",
    "benefit-8": "Sense of Cohesion and Belonging – Become part of a community that supports social change and the continuous development of its members",
    "btn-fill-form": "Fill out the participation form",
    "btn-go-back": "Go back",
    "form-name": "Your Name",
    "contact-email": "Your Email",
    "contact-message": "Your Message",
    "contact-submit": "Send",
    "info-title": "Contact Information",
    "info-address": "Address:<br> Lambrou Katsoni 51, Athens, P.C. 11471",
    "info-phone": "Phone:<br> +30 211 2154573 ",
    "info-email": "Email:<br> amkeinteraction@gmail.com",
    "follow-title": "Follow Us",
    "social-facebook": "Facebook",
    "social-instagram": "Instagram",
    "social-google": "Google Business",
    "btn-sponsor": "Become a Sponsor",
    "join-sponsor-label": "Become a Sponsor:",
    "join-sponsor-text": "Your support as a sponsor is vital for the implementation of our actions. Your contribution, whether financial or in kind, allows us to turn our vision into reality and successfully complete projects with significant impact. As a sponsor, you strengthen our work while promoting your business, connecting it with values such as culture, social contribution, and innovation. It's an opportunity to demonstrate your corporate responsibility and become a co-creator in initiatives that inspire and make a difference.",
    "join-us-sponsor-description": "As a sponsor, you promote your business by connecting it with culture, social contribution, and innovation. Show your corporate responsibility and become a co-creator of change.",
    "join-us-sponsor": "Become a sponsor:",

    // Cookie Consent Translations (Αγγλικά)
    "cookie-message": "This website uses cookies to ensure you get the best experience on our website.",
    "cookie-accept": "Accept Cookies",
    "cookie-deny": "Deny",
    "cookie-learn-more": "Learn more",
    "cookie-privacy-policy-url": "en1.pdf",
    "accept-terms-text": "Read and accept our <a href=\"en2.pdf\" target=\"_blank\">Terms of Use</a> and <a href=\"en3.pdf\" target=\"_blank\">Privacy Policy</a>."

  }
};

// Αυτή η συνάρτηση εφαρμόζει τις μεταφράσεις στα στοιχεία της σελίδας
function applyLanguage(lang) {
  document.querySelectorAll('[data-lang-key]').forEach(el => {
    const key = el.getAttribute('data-lang-key');
    const translation = translations[lang][key];

    if (!translation) return;

    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
      el.placeholder = translation;
    } else {
      el.innerHTML = translation;
    }
  });
}

// ΝΕΑ ΣΥΝΑΡΤΗΣΗ: Ενημερώνει το cookie consent banner με τη νέα γλώσσα
function updateCookieConsentLanguage(lang) {
    // Ελέγχουμε αν η βιβλιοθήκη cookieconsent έχει φορτωθεί και είναι διαθέσιμη
    if (typeof window.cookieconsent === 'undefined' || typeof window.cookieconsent.initialise === 'undefined') {
        console.warn("Cookie consent library not loaded or not fully initialized, cannot update language.");
        return;
    }

    const langContent = translations[lang];

    if (!langContent) {
        console.error(`Translations for language "${lang}" not found.`);
        return;
    }

    // ΠΡΟΣΘΗΚΗ: Ρητή αφαίρεση ΟΛΩΝ των στοιχείων του banner από το DOM
    const cookieBanners = document.querySelectorAll('.cc-window');
    cookieBanners.forEach(banner => {
        banner.remove();
        console.log('Existing cookie consent banner element explicitly removed from DOM.');
    });

    // Αφαίρεση τυχόν κουμπιών ανάκλησης
    const revokeButtons = document.querySelectorAll('.cc-revoke');
    revokeButtons.forEach(button => {
        button.remove();
        console.log('Existing cookie consent revoke button explicitly removed from DOM.');
    });

    // Καταστρέφουμε την υπάρχουσα βιβλιοθήκη αν υπάρχει (καλή πρακτική)
    if (window.cookieconsent.getCookieConsentInstance) {
        const instance = window.cookieconsent.getCookieConsentInstance();
        if (instance && typeof instance.destroy === 'function') {
            instance.destroy(); // Καταστρέφει το υπάρχον banner
            console.log('Existing cookie consent banner instance destroyed via method.');
        }
    }

    // Και τώρα το επανα-αρχικοποιούμε με τις νέες μεταφράσεις
    window.cookieconsent.initialise({
        "palette": {
            "popup": { "background": "#2C3E50", "text": "#FFFFFF" },
            "button": { "background": "#F4D35E", "text": "#2C3E50" }
        },
        "theme": "base",
        "content": {
            "message": langContent["cookie-message"],
            "dismiss": langContent["cookie-accept"],
            "deny": langContent["cookie-deny"],
            "link": langContent["cookie-learn-more"],
            "href": langContent["cookie-privacy-policy-url"]
        },
        "type": "opt-in",
        "revokable": false, // <-- ΑΛΛΑΞΕ ΑΥΤΟ ΤΟ TRUE ΣΕ FALSE
        "position": "bottom",
        "onStatusChange": function(status, chosenBefore) {
          console.log('Cookie consent status changed:', status, 'chosenBefore:', chosenBefore);
        },
        "onInitialise": function(status) {
          console.log('Cookie consent banner re-initialized with status: ', status);
        }
    });
}


function setLanguage(lang) {
  localStorage.setItem("language", lang); // Αποθήκευση γλώσσας
  applyLanguage(lang); // Εφαρμογή γλώσσας στην υπόλοιπη σελίδα
  updateCookieConsentLanguage(lang); // Εφαρμογή γλώσσας στο cookie banner
}

// Χειρισμός εμφάνισης του menu
function toggleMenu() {
  const nav = document.getElementById("main-nav");
  nav.classList.toggle("open");
}

document.documentElement.classList.add("lang-loading");

document.addEventListener("DOMContentLoaded", () => {
    // Εφαρμόζουμε τη γλώσσα μόλις φορτώσει το DOM, καλώντας την setLanguage
    const savedLang = localStorage.getItem("language") || "el";
    document.documentElement.lang = savedLang;
    document.documentElement.setAttribute("data-language", savedLang);
    setLanguage(savedLang); // Καλεί την setLanguage για να αρχικοποιήσει και το banner των cookies
    document.documentElement.classList.remove("lang-loading");
});
